name: doctor
description: Мобильное приложение Кивач

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.5
  dio: ^5.3.1
  flutter_bloc: ^8.1.3
  get_it: ^7.6.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  equatable: ^2.0.5
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.1
  local_auth: ^2.1.6
  webview_flutter: ^4.2.2
  crypto: ^3.0.3
  animations: ^2.0.7
  local_auth_android: ^1.0.32
#  qr_mobile_vision: ^4.1.3
  qr_code_scanner: ^1.0.1
  flutter_svg: ^2.0.7
  smooth_page_indicator: ^1.1.0
  logger: ^2.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  freezed: ^2.3.5
  json_serializable: ^6.7.1
  hive_generator: ^2.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/images/
